theme: minima
title: My Personal Blog
author: NKSL2001
description: A site to learn GitHub Jekyll!
url: https://nksl2001.github.io
baseurl: /skills-github-pages
collections:
  informative:
    output: true